import { Child } from './app/shared/models/child';

export const child: Child[] = [
  {
    id: 'child1',
    firstName: 'Katleen',
    lastName: 'Dela Cruz',
    purok: '2',
    gender: 'Female',
    weight: 17,
    height: 98,
    barangay: 'Bangad',
    dateOfBirth: '11-26-2020',
    photoPath: 'assets/img/photo1.jpg',
    vaccinations: [
      {
        vaccineType: 'BCG',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '12-02-2020',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Hepatitis B Vaccine',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '12-09-2020',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Pentavalent Vaccine',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '02-03-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Oral Polio Vaccine (OPV)',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '02-03-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Pentavalent Vaccine',
        doseNumber: '2nd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '03-10-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Oral Polio Vaccine (OPV)',
        doseNumber: '2nd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '03-10-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Pentavalent Vaccine',
        doseNumber: '3rd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '04-14-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Oral Polio Vaccine (OPV)',
        doseNumber: '3rd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '04-14-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Inactivated Polio Vaccine (IPV)',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '04-14-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Inactivated Polio Vaccine (IPV)',
        doseNumber: '2nd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '07-28-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Pneumococcal Conjugate Vaccine (PCV)',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '02-03-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Pneumococcal Conjugate Vaccine (PCV)',
        doseNumber: '2nd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '03-10-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Pneumococcal Conjugate Vaccine (PCV)',
        doseNumber: '3rd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '04-14-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Measles, Mumps, Rubella Vaccine (MMR)',
        doseNumber: '1st Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '09-01-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
      {
        vaccineType: 'Measles, Mumps, Rubella Vaccine (MMR)',
        doseNumber: '2nd Dose',
        placeOfVaccination: 'Barangay Health Center',
        dateOfVaccination: '11-24-2021',
        midwifeId: 'midwife1',
        bhwId: 'bhw1',
      },
    ],
    isFullyVaccinated: true,
    dateFullyVaccinated: '11-24-2021',
    weighingHistory: [
      {
        date: '01-25-2024',
        weight: 17,
        height: 98,
        weightForAgeStatus: 'Normal',
        heightForAgeStatus: 'Normal',
        weightForLengthHeightStatus: 'Normal',
        notes: 'Annual check-up',
      },
    ],
  },
];
